"""
Add ContractDailyWorkContentModel

Revision ID: 33472240a881
Revises: 55_add_ordering_contract_links
Create Date: 2026-08-06 06:22:14.933612+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

# Revision identifiers used by Alembic
revision: str = '33472240a881'
down_revision: str | Sequence[str] | None = '55_add_ordering_contract_links'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genba_equipments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('genba_id', sa.UUID(), nullable=False),
    sa.Column('equipment_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['genba_id'], ['genba.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_daily_work_contents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('area', sa.String(length=200), nullable=False),
    sa.Column('work_content', sa.String(length=200), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_daily_work_contents_contract_id'), 'contract_daily_work_contents', ['contract_id'], unique=False)
    op.drop_index('ix_genba_equipment_genba_id', table_name='genba_equipment')
    op.drop_table('genba_equipment')
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('audit_logs', 'is_sensitive',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type_entity_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_is_sensitive', table_name='audit_logs', postgresql_where='(is_sensitive = true)')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_cleaning_work_standards_genba_id', table_name='cleaning_work_standards')
    op.drop_index('uq_contract_holiday_rule_type_active', table_name='contract_holiday_rules', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('contract_ordering_link_work_items', 'scope_detail',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index('ix_colwi_link_id', table_name='contract_ordering_link_work_items')
    op.drop_index('ix_colwi_work_content_id', table_name='contract_ordering_link_work_items')
    op.create_index(op.f('ix_contract_ordering_link_work_items_link_id'), 'contract_ordering_link_work_items', ['link_id'], unique=False)
    op.create_index(op.f('ix_contract_ordering_link_work_items_work_content_id'), 'contract_ordering_link_work_items', ['work_content_id'], unique=False)
    op.alter_column('contract_ordering_links', 'remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index('ix_col_ordering_contract_id', table_name='contract_ordering_links')
    op.drop_index('ix_col_receiving_contract_id', table_name='contract_ordering_links')
    op.drop_constraint('uq_ordering_receiving_link', 'contract_ordering_links', type_='unique')
    op.create_index(op.f('ix_contract_ordering_links_ordering_contract_id'), 'contract_ordering_links', ['ordering_contract_id'], unique=False)
    op.create_index(op.f('ix_contract_ordering_links_receiving_contract_id'), 'contract_ordering_links', ['receiving_contract_id'], unique=False)
    op.drop_constraint('uq_contract_periodic_schedule', 'contract_periodic_schedule', type_='unique')
    op.drop_index('ix_contract_periodic_schedule_contract_id', table_name='contract_periodic_schedule')
    op.create_index(op.f('ix_contract_periodic_schedule_contract_id'), 'contract_periodic_schedule', ['contract_id'], unique=True)
    op.drop_index('ix_contracts_genba_id', table_name='contracts')
    op.drop_index('ix_contracts_genba_service_category', table_name='contracts')
    op.drop_index('ix_contracts_status', table_name='contracts')
    op.drop_index('ix_customer_contacts_customer_id', table_name='customer_contacts')
    op.drop_index('ix_entry_exit_instructions_genba_id', table_name='entry_exit_instructions')
    op.drop_index('idx_genba_address_trgm', table_name='genba', postgresql_using='gin')
    op.drop_index('idx_genba_property_name_trgm', table_name='genba', postgresql_using='gin')
    op.drop_index('ix_genba_customer_id', table_name='genba')
    op.drop_index('ix_genba_status', table_name='genba')
    op.drop_index('ix_genba_custom_holidays_genba_id', table_name='genba_custom_holidays')
    op.alter_column('genba_photos', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_genba_photos_genba_id', table_name='genba_photos')
    op.drop_index('ix_genba_photos_type', table_name='genba_photos')
    op.drop_constraint('uq_genba_staff_assignments', 'genba_staff_assignments', type_='unique')
    op.drop_constraint('uq_genba_workers', 'genba_workers', type_='unique')
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_invoices_contract', table_name='invoices')
    op.drop_index('idx_invoices_period', table_name='invoices')
    op.drop_constraint('uq_invoice_contract_period', 'invoices', type_='unique')
    op.alter_column('key_infos', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_key_infos_genba_id', table_name='key_infos')
    op.drop_index('ix_memo_attachments_memo_id', table_name='memo_attachments')
    op.drop_index('ix_memos_genba_id', table_name='memos')
    op.drop_index('ix_periodic_cleaning_details_plan_id', table_name='periodic_cleaning_details')
    op.drop_index('ix_periodic_cleaning_plans_genba_id', table_name='periodic_cleaning_plans')
    op.alter_column('quotations', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quotations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('quotations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('uq_users_email', table_name='users', postgresql_where='(email IS NOT NULL)')
    op.drop_index('uq_users_username', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_constraint('fk_users_related_staff', 'users', type_='foreignkey')
    op.alter_column('work_schedules', 'holiday_rule',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'OFF'::character varying"))
    op.drop_index('ix_work_schedules_genba_id', table_name='work_schedules')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration. MUST be implemented — see BE§7."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_work_schedules_genba_id', 'work_schedules', ['genba_id'], unique=False)
    op.alter_column('work_schedules', 'holiday_rule',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'OFF'::character varying"))
    op.create_foreign_key('fk_users_related_staff', 'users', 'staff', ['related_entity_id'], ['id'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('uq_users_username', 'users', ['username'], unique=True)
    op.create_index('uq_users_email', 'users', ['email'], unique=True, postgresql_where='(email IS NOT NULL)')
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'INTERNAL_STAFF'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('quotations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('quotations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('quotations', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.create_index('ix_periodic_cleaning_plans_genba_id', 'periodic_cleaning_plans', ['genba_id'], unique=False)
    op.create_index('ix_periodic_cleaning_details_plan_id', 'periodic_cleaning_details', ['plan_id'], unique=False)
    op.create_index('ix_memos_genba_id', 'memos', ['genba_id'], unique=False)
    op.create_index('ix_memo_attachments_memo_id', 'memo_attachments', ['memo_id'], unique=False)
    op.create_index('ix_key_infos_genba_id', 'key_infos', ['genba_id'], unique=False)
    op.alter_column('key_infos', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_unique_constraint('uq_invoice_contract_period', 'invoices', ['contract_id', 'billing_period_year', 'billing_period_month', 'invoice_type'])
    op.create_index('idx_invoices_period', 'invoices', ['billing_period_year', 'billing_period_month'], unique=False)
    op.create_index('idx_invoices_contract', 'invoices', ['contract_id'], unique=False)
    op.alter_column('invoices', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.create_unique_constraint('uq_genba_workers', 'genba_workers', ['genba_id', 'worker_id'])
    op.create_unique_constraint('uq_genba_staff_assignments', 'genba_staff_assignments', ['genba_id', 'staff_id'])
    op.create_index('ix_genba_photos_type', 'genba_photos', ['genba_id', 'photo_type'], unique=False)
    op.create_index('ix_genba_photos_genba_id', 'genba_photos', ['genba_id'], unique=False)
    op.alter_column('genba_photos', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index('ix_genba_custom_holidays_genba_id', 'genba_custom_holidays', ['genba_id'], unique=False)
    op.create_index('ix_genba_status', 'genba', ['status'], unique=False)
    op.create_index('ix_genba_customer_id', 'genba', ['customer_id'], unique=False)
    op.create_index('idx_genba_property_name_trgm', 'genba', ['property_name'], unique=False, postgresql_using='gin')
    op.create_index('idx_genba_address_trgm', 'genba', ['address'], unique=False, postgresql_using='gin')
    op.create_index('ix_entry_exit_instructions_genba_id', 'entry_exit_instructions', ['genba_id'], unique=False)
    op.create_index('ix_customer_contacts_customer_id', 'customer_contacts', ['customer_id'], unique=False)
    op.create_index('ix_contracts_status', 'contracts', ['status'], unique=False)
    op.create_index('ix_contracts_genba_service_category', 'contracts', ['genba_id', 'service_category'], unique=False)
    op.create_index('ix_contracts_genba_id', 'contracts', ['genba_id'], unique=False)
    op.drop_index(op.f('ix_contract_periodic_schedule_contract_id'), table_name='contract_periodic_schedule')
    op.create_index('ix_contract_periodic_schedule_contract_id', 'contract_periodic_schedule', ['contract_id'], unique=False)
    op.create_unique_constraint('uq_contract_periodic_schedule', 'contract_periodic_schedule', ['contract_id'])
    op.drop_index(op.f('ix_contract_ordering_links_receiving_contract_id'), table_name='contract_ordering_links')
    op.drop_index(op.f('ix_contract_ordering_links_ordering_contract_id'), table_name='contract_ordering_links')
    op.create_unique_constraint('uq_ordering_receiving_link', 'contract_ordering_links', ['ordering_contract_id', 'receiving_contract_id'])
    op.create_index('ix_col_receiving_contract_id', 'contract_ordering_links', ['receiving_contract_id'], unique=False)
    op.create_index('ix_col_ordering_contract_id', 'contract_ordering_links', ['ordering_contract_id'], unique=False)
    op.alter_column('contract_ordering_links', 'remarks',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_contract_ordering_link_work_items_work_content_id'), table_name='contract_ordering_link_work_items')
    op.drop_index(op.f('ix_contract_ordering_link_work_items_link_id'), table_name='contract_ordering_link_work_items')
    op.create_index('ix_colwi_work_content_id', 'contract_ordering_link_work_items', ['work_content_id'], unique=False)
    op.create_index('ix_colwi_link_id', 'contract_ordering_link_work_items', ['link_id'], unique=False)
    op.alter_column('contract_ordering_link_work_items', 'scope_detail',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('uq_contract_holiday_rule_type_active', 'contract_holiday_rules', ['contract_id', 'rule_type'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_index('ix_cleaning_work_standards_genba_id', 'cleaning_work_standards', ['genba_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_is_sensitive', 'audit_logs', ['is_sensitive'], unique=False, postgresql_where='(is_sensitive = true)')
    op.create_index('ix_audit_logs_entity_type_entity_id', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.alter_column('audit_logs', 'is_sensitive',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table('genba_equipment',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('genba_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('equipment_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genba_id'], ['genba.id'], name='genba_equipment_genba_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='genba_equipment_pkey')
    )
    op.create_index('ix_genba_equipment_genba_id', 'genba_equipment', ['genba_id'], unique=False)
    op.drop_index(op.f('ix_contract_daily_work_contents_contract_id'), table_name='contract_daily_work_contents')
    op.drop_table('contract_daily_work_contents')
    op.drop_table('genba_equipments')
    # ### end Alembic commands ###
